version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  # TODO: add your code here (delete this line and follow the indent conventions)
  app:
    # TODO: you will need to add to this
    environment:
      - REDIS_HOST=redis
    build: ./backend
    ports:
      - "9900:9900"
  frontend:
    # TODO: you will need to add to this
    build: ./frontend
    ports:
      - "3901:3000" 
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5555 
    depends_on:
      - app
